<?php

/**
 * @file
 * Contains mbmc_carrousel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_help().
 */
function mbmc_carrousel_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the mbmc_carrousel module.
        case 'help.page.mbmc_carrousel':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Carousel of images') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function mbmc_carrousel_theme()
{
    return [
        'paragraph__lib_v2_carousel__default' => [
            'render element' => 'children',
        ],
    ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function mbmc_carrousel_theme_suggestions_block_alter(array&$suggestions, array $variables, $hook)
{
    if (isset($variables['elements']['content']['#block_content'])) {
        array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#block_content']->bundle());
    }
}

function mbmc_carrousel_preprocess_paragraph(&$variables)
{
    // dump($variables);
    // die;

    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['paragraph'];
    // Get the type
    $parentBundle = $paragraph->bundle();

    if ("lib_v2_carousel" == $parentBundle) {
        foreach ($paragraph->get('field_lib_v2_carousel_group_ref')->getValue() as $clave => $element) {
            $p = \Drupal\paragraphs\Entity\Paragraph::load($element['target_id']);
            $variables['card_carrusel'][$clave]['subheading'] = $p->field_lib_v2_carousel_sec->getValue()[0]['value'];
            $variables['card_carrusel'][$clave]['title'] = $p->field_lib_v2_carousel_text_main->getValue()[0]['value'];
            $variables['card_carrusel'][$clave]['subtitle'] = $p->field_lib_v2_carousel_text_sup->getValue()[0]['value'];
            $variables['card_carrusel'][$clave]['link']['uri'] = $p->field_lib_v2_carousel_link->getValue()[0]['uri'];
            $variables['card_carrusel'][$clave]['link']['text'] = $p->field_lib_v2_carousel_link->getValue()[0]['title'];
            $fid = $p->field_lib_v2_carousel_image->getValue()[0]['target_id'];
            $media = Media::load($fid);
            $fid = $media->getSource()->getSourceFieldValue($media);
            $file = File::load($fid);
            $variables['card_carrusel'][$clave]['imagen'] = file_create_url($file->getFileUri());
        }
    }

}
