features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
breadcrumb_separator: fa-angle-right
page_container_border: 1
fixed_header: 1
scroll_to_top_display: 1
scroll_to_top_icon: fa-angle-up
scroll_to_top_region: footer-to-top-enabled
bootstrap_remote_type: cdn
premium_description: ''
