_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
langcode: es
smtp_on: true
smtp_host: smtp.hostinger.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: webmaster@mibienestarmicompromiso.com
smtp_password: 'Webmaster2022*'
smtp_from: webmaster@mibienestarmicompromiso.com
smtp_fromname: Webmaster
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
